import 'package:cotor/features/add_tutee_assignment/bloc/edit_tutee_assignment_bloc.dart';
import 'package:cotor/features/auth_service/bloc/auth_service_bloc/auth_service_bloc.dart';
import 'package:cotor/features/edit_tutor_profile/bloc/edit_tutor_profile_bloc.dart';
import 'package:cotor/features/request_tutor/request_tutor_form/bloc/request_tutor_form_bloc.dart';
import 'package:cotor/features/request_tutor/select_existing_assignment/bloc/select_existing_assignment_bloc.dart';
import 'package:cotor/features/user_profile_bloc/user_profile_bloc.dart';
import 'package:cotor/features/view_assignment/bloc/view_assignment_bloc.dart';
import 'package:cotor/features/view_tutor_profile/bloc/view_tutor_profile_bloc.dart';
import 'package:cotor/injection_container.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

/// Used to create user-dependent objects that need to be accessible by all widgets.
/// This widgets should live above the [MaterialApp].
/// See [InitialPageDecider], a descendant widget that consumes the snapshot generated by this builder.
class UserDataInjector extends StatelessWidget {
  const UserDataInjector({
    Key key,
    @required this.builder,
  }) : super(key: key);
  final Widget Function(BuildContext, AuthServiceState) builder;

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<AuthServiceBloc, AuthServiceState>(
      builder: (context, state) {
        if (state is Authenticated) {
          return MultiBlocProvider(providers: [
            BlocProvider<UserProfileBloc>(
              create: (context) =>
                  sl<UserProfileBloc>()..add(UserEnterHompage()),
            ),
            BlocProvider<ViewAssignmentBloc>(
              create: (context) => sl<ViewAssignmentBloc>(),
            ),
            BlocProvider<ViewTutorProfileBloc>(
              create: (context) => sl<ViewTutorProfileBloc>(),
            ),
            BlocProvider<EditTutorProfileBloc>(
              create: (context) => sl<EditTutorProfileBloc>(),
            ),
            BlocProvider<EditTuteeAssignmentBloc>(
              create: (context) => sl<EditTuteeAssignmentBloc>(),
            ),
            BlocProvider<SelectExistingAssignmentBloc>(
              create: (context) => sl<SelectExistingAssignmentBloc>(),
            ),
            BlocProvider<RequestTutorFormBloc>(
              create: (context) => sl<RequestTutorFormBloc>(),
            )
          ], child: builder(context, state));
        } else {
          return builder(context, state);
        }
      },
    );
  }
}
